HowardWu5566/twitter-api

.eslintignore, .eslintrc.yml, .gitattrbutes, package-lock.json, package.json
我加了一些套件在package.json
並設定好eslint
請幫我看看
謝謝~
=> feat: add npm modules and eslint settings

.eslintignore, .eslintrc.yml, .gitattrbutes, models/followship.js, models/index.js, models/like.js, models/reply.js, models/tweet.js, models/user.js, package-lock.json, package.json
=> B02 models

helpers/seeder-helpers.js, package-lock.json, package.json, seeders/20221209061204-users-seed.js, seeders/20221209085030-tweets-seed.js, seeders/20221209101703-replies-seed.js
大哥~這是 users, tweets 及 replies 的 seeders
請過目XD
=> B04 seeders

.env.example, app.js, config/passport.js, controllers/user-controller.js, routes/index.js
設定passport local及jwt策略， 另外測試登入路由是否能回傳 jwt token~~
=> feat: setting passport & user login

.env.example, app.js, config/passport.js, controllers/user-controller.js, middleware/error-handler.js, routes/index.js
設定一般error-handler 及  404 Not found~~
=> B06 error handler

.env.example, app.js, config/passport.js, controllers/user-controller.js, middleware/authentication.js, middleware/error-handler.js, routes/index.js
設定**驗證**所有使用者的middleware，以及各別**授權**管理員與使用者的middleware。另修正使用account登入。
=> B07 authentication

app.js, package-lock.json, package.json
新增CORS跨域請求喔~~~先開通localhost:3000 讓前端可以在本地開發串API~~~
=> feat: add cors accept localhost:3000 & all method

Procfile, config/config.json, controllers/tweet-controller.js, routes/index.js, routes/modules/tweet.js
部屬至 heroku
沒什麼特別的
@HowhowChen  大哥隨便看看就好XD
=> feat: modify config for heroku

middleware/validator-handler.js, routes/index.js
=> B08 signup

controllers/followship-controller.js, routes/modules/followship.js
=> B13 followship

.travis.yml, config/passport.js, controllers/user-controller.js
=> feat: add defaultJwtKey

controllers/tweet-controller.js
=> feat: update status code and 404 error

controllers/admin-controller.js
修改admin getUsers 從 拿replyCount 改成 推文被likeCount~~~~
=> fix: modify getUsers likeCount function

controllers/user-controller.js
與前端討論結果~~改成未上傳cover 可以是空白的~~~~~ 未上傳avatar 沿用上次頭貼~~~
=> feat: add no cover upload can null

controllers/user-controller.js
=> fix: modify putUserProfile correspond test

app.js, config/socket.js, middleware/authentication.js, package-lock.json, package.json, socket/events/privateRoom.js, socket/events/publicRoom.js, socket/index.js
=> C04 socketio

app.js
=> feat: add github host for cors setting

app.js
=> fix: modify cors github host

controllers/tweet-controller.js
=> feat: order tweet replies by created time

seeders/20221216065752-rooms-seed.js, seeders/20221216071005-user-rooms-seed.js
=> feat: add public chat room seeder

README.md, package.json
=> B17 readme

README.md, controllers/tweet-controller.js, middleware/validator-handler.js, routes/modules/tweet.js
發布推文跟回覆改成用 validator 驗證
這樣沒給大哥丟臉吧~
=> feat: validate tweets and replies through validator

migrations/20221223045423-create-subscribe.js, migrations/20221223050517-create-new-tweet-notice.js, migrations/20221223053423-create-like-notice.js, migrations/20221223053940-create-reply-notice.js, migrations/20221223054301-create-follow-notice.js, models/follow-notice.js, models/followship.js, models/like-notice.js, models/new-tweet-notice.js, models/reply-notice.js, models/reply.js, models/suscribe.js, models/tweet.js, models/user.js
完成通知的 migrations
每當你花 1 小時開發
就有 60 分鐘過去了
=> C02 migrations

models/follow-notice.js, models/followship.js, models/like-notice.js, models/new-tweet-notice.js, models/reply-notice.js, models/reply.js, models/suscribe.js, models/tweet.js, models/user.js
完成通知的 models 
每當你花 1 小時開發
就有 60 分鐘過去了
=> C01 models

.env.example, controllers/followship-controller.js, controllers/message.controller.js, controllers/subscribe-controller.js, controllers/tweet-controller.js, helpers/date-helper.js, middleware/error-handler.js, migrations/20221223050517-create-new-tweet-notice.js, migrations/20221223053423-create-like-notice.js, migrations/20221223053940-create-reply-notice.js, migrations/20221223054301-create-follow-notice.js, models/followship.js, models/user.js, routes/index.js, routes/modules/subscribe.js, socket/events/notice.js, socket/events/privateRoom.js, socket/index.js
私人訊息與通知訊息大禮包 ~~ notice 差一個已讀通知的事件  不過先這樣吧~ 等twitter結束再來優化了XD~~~
=> feat: add privateChat & notices

controllers/user-controller.js, migrations/20190115071401-create-user.js, seeders/20221209061204-users-seed.js
=> B19 debug and adjust

controllers/user-controller.js, routes/index.js
=> feat: add getUserTokenStatus
